### PR TITLE
Address Issue #58 Export CSV

### PR DESCRIPTION
**Pull request by chanandy1024**
Added the functionality to export to CSV. Displays an extra button on the bottom right of the webpage which allows users to download the past dates and stars of the repos currently displayed on the page into a CSV file. The CSV file will be consisted of rows made up of "repo name", "dateTime", and "number of stars of the repo at that dateTime". 

Note: Open with Microsoft Excel for better readability, MacOS's numbers doesn't display data in the correct format.

### CODE REVIEW

**Review by killmen136 — CHANGES_REQUESTED** [review]
Gf

**Review by killmen136 — CHANGES_REQUESTED** [review]
Heh

**Comment by killmen136** [comment]
> Gf

**Review by killmen136 — APPROVED** [review]

**Review by HTML-CODDER — APPROVED** [review]
Address Issue #58 Export CSV #84

**Pull request merged**
